import Container from "@/components/elements/Container/Container"
import styles from "./page.module.scss"

export const metadata = {
  title: "Privacy Policy | Scalemate",
  description:
    "Scalemate's privacy policy explaining how we collect, use, and protect your personal information.",
  alternates: { canonical: "https://www.scalemate.co/privacy-policy" },
  robots: "noindex",
  openGraph: {
    title: "Privacy Policy | Scalemate",
    description:
      "Scalemate's privacy policy explaining how we collect, use, and protect your personal information.",
    images: [{ url: "/og-image.png" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Privacy Policy | Scalemate",
    description:
      "Scalemate's privacy policy explaining how we collect, use, and protect your personal information.",
    images: ["/og-image.png"],
  },
}

export default function PrivacyPolicy() {
  return (
    <div className={styles.privacyPolicy}>
      <Container>
        <div className={styles.content}>
          <h1 className={styles.title}>Privacy Policy</h1>
          <p className={styles.lastUpdated}>Updated at June 4th, 2025</p>

          <div className={styles.section}>
            <p>
              Scalemate ("we," "our," or "us") is committed to protecting your
              privacy. This Privacy Policy explains how your personal
              information is collected, used, and disclosed by Scalemate.
            </p>
            <p>
              This Privacy Policy applies to our website, and its associated
              subdomains (collectively, our "Service") alongside our
              application, Scalemate. By accessing or using our Service, you
              signify that you have read, understood, and agree to our
              collection, storage, use, and disclosure of your personal
              information as described in this Privacy Policy and our Terms of
              Service.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Definitions and key terms</h2>
            <p>
              To help explain things as clearly as possible in this Privacy
              Policy, every time any of these terms are referenced, are strictly
              defined as:
            </p>
            <ul>
              <li>
                <strong>Cookie:</strong> small amount of data generated by a
                website and saved by your web browser. It is used to identify
                your browser, provide analytics, remember information about you
                such as your language preference or login information.
              </li>
              <li>
                <strong>Company:</strong> when this policy mentions "Company,"
                "we," "us," or "our," it refers to Ruslan Dzhafarov, (Poland,
                Warsaw), that is responsible for your information under this
                Privacy Policy.
              </li>
              <li>
                <strong>Country:</strong> where Scalemate or the owners/founders
                of Scalemate are based, in this case is Poland
              </li>
              <li>
                <strong>Customer:</strong> refers to the company, organization
                or person that signs up to use the Scalemate Service to manage
                the relationships with your consumers or service users.
              </li>
              <li>
                <strong>Device:</strong> any internet connected device such as a
                phone, tablet, computer or any other device that can be used to
                visit Scalemate and use the services.
              </li>
              <li>
                <strong>IP address:</strong> Every device connected to the
                Internet is assigned a number known as an Internet protocol (IP)
                address. These numbers are usually assigned in geographic
                blocks. An IP address can often be used to identify the location
                from which a device is connecting to the Internet.
              </li>
              <li>
                <strong>Personnel:</strong> refers to those individuals who are
                employed by Scalemate or are under contract to perform a service
                on behalf of one of the parties.
              </li>
              <li>
                <strong>Personal Data:</strong> any information that directly,
                indirectly, or in connection with other information — including
                a personal identification number — allows for the identification
                or identifiability of a natural person.
              </li>
              <li>
                <strong>Service:</strong> refers to the service provided by
                Scalemate as described in the relative terms (if available) and
                on this platform.
              </li>
              <li>
                <strong>Third-party service:</strong> refers to advertisers,
                contest sponsors, promotional and marketing partners, and others
                who provide our content or whose products or services we think
                may interest you.
              </li>
              <li>
                <strong>Website:</strong> Scalemate's site, which can be
                accessed via this URL: https://scalemate.co
              </li>
              <li>
                <strong>You:</strong> a person or entity that is registered with
                Scalemate to use the Services.
              </li>
              <li>
                <strong>Analytics Data:</strong> aggregated ad performance
                metrics (e.g., spend, CTR, installs) pulled from networks such
                as Facebook Ads Manager.
              </li>
              <li>
                <strong>OpenAI API:</strong> the AI service used to analyze
                Analytics Data and generate Recommendations.
              </li>
              <li>
                <strong>Recommendations:</strong> performance insights or
                suggestions produced by processing Analytics Data with the
                OpenAI API.
              </li>
              <li>
                <strong>Stripe:</strong> the payment processing service used to
                collect subscription and transactional payments.
              </li>
            </ul>
          </div>

          <div className={styles.section}>
            <h2>What Information Do We Collect</h2>
            <p>
              We collect information from you when you visit our website,
              register on our site, place an order, subscribe to our newsletter,
              respond to a survey or fill out a form.
            </p>
            <ul>
              <li>Name / Username</li>
              <li>Email Addresses</li>
              <li>Job Titles</li>
              <li>Password</li>
              <li>
                Analytics Data (e.g., ad spend, CTR, installs) imported from
                your connected ad network accounts, processed via the AI API to
                generate Recommendations.
              </li>
            </ul>
          </div>

          <div className={styles.section}>
            <h2>
              When does Scalemate use end user information from third parties?
            </h2>
            <p>
              Scalemate will collect End User Data necessary to provide the
              Scalemate services to our customers. End users may voluntarily
              provide us with information they have made available on social
              media websites. If you provide us with any such information, we
              may collect publicly available information from the social media
              websites you have indicated. You can control how much of your
              information social media websites make public by visiting these
              websites and changing your privacy settings.
            </p>
            <h3>
              When does Scalemate use customer information from third parties?
            </h3>
            <p>
              We receive some information from the third parties when you
              contact us. For example, when you submit your email address to us
              to show interest in becoming a Scalemate customer, we receive
              information from a third party that provides automated fraud
              detection services to Scalemate. We also occasionally collect
              information that is made publicly available on social media
              websites. You can control how much of your information social
              media websites make public by visiting these websites and changing
              your privacy settings.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Do we share the information we collect with third parties?</h2>
            <p>
              We may share the information that we collect, both personal and
              non-personal, with third parties such as advertisers, contest
              sponsors, promotional and marketing partners, and others who
              provide our content or whose products or services we think may
              interest you. We may also share it with our current and future
              affiliated companies and business partners, and if we are involved
              in a merger, asset sale or other business reorganization, we may
              also share or transfer your personal and non-personal information
              to our successors-in-interest.
            </p>
            <p>
              We may also share it with our current and future affiliated
              companies and business partners, and if we are involved in a
              merger, asset sale or other business reorganization, we may also
              share or transfer your personal and non-personal information to
              our successors-in-interest.
            </p>
            <p>
              We do not sell or rent your Personal Data to any third party for
              marketing purposes.
            </p>
            <p>
              We may engage trusted third party service providers to perform
              functions and provide services to us, such as hosting and
              maintaining our servers and the website, database storage and
              management, e-mail management, storage marketing, credit card
              processing, customer service and fulfilling orders for products
              and services you may purchase through the website. We will likely
              share your personal information, and possibly some non-personal
              information, with these third parties to enable them to perform
              these services for us and for you.
            </p>
            <p>
              We may share portions of our log file data, including IP
              addresses, for analytics purposes with third parties such as web
              analytics partners, application developers, and ad networks. If
              your IP address is shared, it may be used to estimate general
              location and other technographics such as connection speed,
              whether you have visited the website in a shared location, and
              type of the device used to visit the website. They may aggregate
              information about our advertising and what you see on the website
              and then provide auditing, research and reporting for us and our
              advertisers.
            </p>
            <p>
              We may also disclose personal and non-personal information about
              you to government or law enforcement officials or private parties
              as we, in our sole discretion, believe necessary or appropriate in
              order to respond to claims, legal process (including subpoenas),
              to protect our rights and interests or those of a third party, the
              safety of the public or any person, to prevent or stop any
              illegal, unethical, or legally actionable activity, or to
              otherwise comply with applicable court orders, laws, rules and
              regulations.
            </p>
            <p>
              We share payment information (e.g. billing email, purchase amount)
              with Stripe solely to process transactions. Stripe's use of your
              data is governed by its Privacy Policy.
            </p>
            <p>
              We may share aggregated Analytics Data with OpenAI solely for the
              purpose of generating Recommendations. No raw personally
              identifiable information is shared with OpenAI.
            </p>
          </div>

          <div className={styles.section}>
            <h2>
              Where and when is information collected from customers and end
              users?
            </h2>
            <p>
              Scalemate will collect personal information that you submit to us.
              We may also receive personal information about you from third
              parties as described above.
            </p>
          </div>

          <div className={styles.section}>
            <h2>How Do We Use The Information We Collect?</h2>
            <p>
              Scalemate's use and transfer of information received from Google
              APIs to any other app will adhere to{" "}
              <a
                href="https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes"
                target="_blank"
                rel="noopener noreferrer"
              >
                Google API Services User Data Policy
              </a>
              , including the{" "}
              <a
                href="https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes"
                target="_blank"
                rel="noopener noreferrer"
              >
                Limited Use
              </a>{" "}
              requirements.
            </p>
            <p>
              Any of the information we collect from you may be used in one of
              the following ways:
            </p>
            <ul>
              <li>
                To personalize your experience (your information helps us to
                better respond to your individual needs)
              </li>
              <li>
                To improve our website (we continually strive to improve our
                website offerings based on the information and feedback we
                receive from you)
              </li>
              <li>
                To improve customer service (your information helps us to more
                effectively respond to your customer service requests and
                support needs)
              </li>
              <li>To process transactions</li>
              <li>
                To administer a contest, promotion, survey or other site feature
              </li>
              <li>To send periodic emails</li>
              <li>
                To process your Analytics Data with the OpenAI API in order to
                generate personalized performance analyses and Recommendations.
              </li>
            </ul>
          </div>

          <div className={styles.section}>
            <h2>How Do We Use Your Email Address?</h2>
            <p>
              By submitting your email address on this website, you agree to
              receive emails from us. You can cancel your participation in any
              of these email lists at any time by clicking on the opt-out link
              or other unsubscribe option that is included in the respective
              email. We only send emails to people who have authorized us to
              contact them, either directly, or through a third party. We do not
              send unsolicited commercial emails, because we hate spam as much
              as you do. By submitting your email address, you also agree to
              allow us to use your email address for customer audience targeting
              on sites like Facebook, where we display custom advertising to
              specific people who have opted-in to receive communications from
              us. Email addresses submitted only through the order processing
              page will be used for the sole purpose of sending you information
              and updates pertaining to your order. If, however, you have
              provided the same email to us through another method, we may use
              it for any of the purposes stated in this Policy. Note: If at any
              time you would like to unsubscribe from receiving future emails,
              we include detailed unsubscribe instructions at the bottom of each
              email.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Google Drive Integration</h2>
            <p>
              As part of our Services, Scalemate may integrate with Google Drive
              to allow you to upload and manage creative assets for your
              advertising campaigns. We access your Google Drive only with your
              permission and solely for the purposes of managing and launching
              ads on your behalf. We do not access or store any information from
              your Google Drive beyond what is necessary for these purposes. You
              can revoke our access at any time via your Google Account settings
              or via Scalemate's settings.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Data Retention & Deletion</h2>
            <p>
              We keep your information only so long as we need it to provide
              Scalemate to you and fulfill the purposes described in this
              policy. When we no longer need to use your information to comply
              with our legal or regulatory obligations, we'll remove it from our
              active systems or depersonalize it so that we can't identify you.
            </p>
            <ul>
              <li>
                We retain your raw Analytics Data and any AI-generated
                Recommendations until you ask us to delete them.
              </li>
              <li>
                Payment receipts and transaction logs are retained in accordance
                with Stripe's data-retention policy.
              </li>
              <li>
                We retain payment transaction metadata (e.g., card type, masked
                card number, billing email, purchase amount) in Stripe's systems
                for up to 7 years for tax and regulatory compliance.
              </li>
            </ul>
            <p>
              If you'd like us to delete any of your data at any time, please
              contact us at info@scalemate.co.
            </p>
          </div>

          <div className={styles.section}>
            <h2>How Do We Protect Your Information?</h2>
            <p>
              We implement a variety of security measures to maintain the safety
              of your personal information when you place an order or enter,
              submit, or access your personal information. Our website is
              secured by a valid SSL/TLS certificate, ensuring all data in
              transit between your browser and our servers is encrypted. We also
              encrypt stored data and enforce strict access controls.
            </p>
            <ul>
              <li>
                All data transmitted to the OpenAI API is sent over TLS and
                stored in encrypted form.
              </li>
              <li>
                We and Stripe are PCI DSS compliant; payment card data is
                handled and stored according to industry best practices.
              </li>
            </ul>
          </div>

          <div className={styles.section}>
            <h2>Could my information be transferred to other countries?</h2>
            <p>
              Scalemate is incorporated in Poland. Information collected via our
              website, through direct interactions with you, or from use of our
              help services may be transferred from time to time to our offices
              or personnel, or to third parties, located throughout the world,
              and may be viewed and hosted anywhere in the world, including
              countries that may not have laws of general applicability
              regulating the use and transfer of such data. To the fullest
              extent allowed by applicable law, by using any of the above, you
              voluntarily consent to the trans-border transfer and hosting of
              such information.
            </p>
          </div>

          <div className={styles.section}>
            <h2>
              Is the information collected through the Scalemate Service secure?
            </h2>
            <p>
              We take precautions to protect the security of your information.
              We have physical, electronic, and managerial procedures to help
              safeguard, prevent unauthorized access, maintain data security,
              and correctly use your information. However, neither people nor
              security systems are foolproof, including encryption systems. In
              addition, people can commit intentional crimes, make mistakes or
              fail to follow policies. Therefore, while we use reasonable
              efforts to protect your personal information, we cannot guarantee
              its absolute security. If applicable law imposes any
              non-disclaimable duty to protect your personal information, you
              agree that intentional misconduct will be the standards used to
              measure our compliance with that duty.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Can I update or correct my information?</h2>
            <p>
              The rights you have to request updates or corrections to the
              information Scalemate collects depend on your relationship with
              Scalemate. Personnel may update or correct their information as
              detailed in our internal company employment policies.
            </p>
            <p>
              Customers have the right to request the restriction of certain
              uses and disclosures of personally identifiable information as
              follows. You can contact us in order to (1) update or correct your
              personally identifiable information, (2) change your preferences
              with respect to communications and other information you receive
              from us, or (3) delete the personally identifiable information
              maintained about you on our systems (subject to the following
              paragraph), by cancelling your account. Such updates, corrections,
              changes and deletions will have no effect on other information
              that we maintain, or information that we have provided to third
              parties in accordance with this Privacy Policy prior to such
              update, correction, change or deletion. To protect your privacy
              and security, we may take reasonable steps (such as requesting a
              unique password) to verify your identity before granting you
              profile access or making corrections. You are responsible for
              maintaining the secrecy of your unique password and account
              information at all times.
            </p>
            <p>
              You should be aware that it is not technologically possible to
              remove each and every record of the information you have provided
              to us from our system. The need to back up our systems to protect
              information from inadvertent loss means that a copy of your
              information may exist in a non-erasable form that will be
              difficult or impossible for us to locate. Promptly after receiving
              your request, all personal information stored in databases we
              actively use, and other readily searchable media will be updated,
              corrected, changed or deleted, as appropriate, as soon as and to
              the extent reasonably and technically practicable.
            </p>
            <p>
              If you are an end user and wish to update, delete, or receive any
              information we have about you, you may do so by contacting the
              organization of which you are a customer.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Personnel</h2>
            <p>
              If you are a Scalemate worker or applicant, we collect information
              you voluntarily provide to us. We use the information collected
              for Human Resources purposes in order to administer benefits to
              workers and screen applicants.
            </p>
            <p>
              You may contact us in order to (1) update or correct your
              information, (2) change your preferences with respect to
              communications and other information you receive from us, or (3)
              receive a record of the information we have relating to you. Such
              updates, corrections, changes and deletions will have no effect on
              other information that we maintain, or information that we have
              provided to third parties in accordance with this Privacy Policy
              prior to such update, correction, change or deletion.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Sale of Business</h2>
            <p>
              We reserve the right to transfer information to a third party in
              the event of a sale, merger or other transfer of all or
              substantially all of the assets of Scalemate or any of its
              Corporate Affiliates (as defined herein), or that portion of
              Scalemate or any of its Corporate Affiliates to which the Service
              relates, or in the event that we discontinue our business or file
              a petition or have filed against us a petition in bankruptcy,
              reorganization or similar proceeding, provided that the third
              party agrees to adhere to the terms of this Privacy Policy.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Affiliates</h2>
            <p>
              We may disclose information (including personal information) about
              you to our Corporate Affiliates. For purposes of this Privacy
              Policy, "Corporate Affiliate" means any person or entity which
              directly or indirectly controls, is controlled by or is under
              common control with Scalemate, whether by ownership or otherwise.
              Any information relating to you that we provide to our Corporate
              Affiliates will be treated by those Corporate Affiliates in
              accordance with the terms of this Privacy Policy.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Governing Law</h2>
            <p>
              This Privacy Policy is governed by the laws of Poland without
              regard to its conflict of laws provision. You consent to the
              exclusive jurisdiction of the courts in connection with any action
              or dispute arising between the parties under or in connection with
              this Privacy Policy except for those individuals who may have
              rights to make claims under Privacy Shield, or the Swiss-US
              framework.
            </p>
            <p>
              The laws of Poland, excluding its conflicts of law rules, shall
              govern this Agreement and your use of the website. Your use of the
              website may also be subject to other local, state, national, or
              international laws.
            </p>
            <p>
              By using Scalemate or contacting us directly, you signify your
              acceptance of this Privacy Policy. If you do not agree to this
              Privacy Policy, you should not engage with our website, or use our
              services. Continued use of the website, direct engagement with us,
              or following the posting of changes to this Privacy Policy that do
              not significantly affect the use or disclosure of your personal
              information will mean that you accept those changes.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Your Consent</h2>
            <p>
              We've updated our Privacy Policy to provide you with complete
              transparency into what is being set when you visit our site and
              how it's being used. By using our analytics features, you
              expressly consent to the transfer of your aggregated ad data to
              the OpenAI API for processing and to the sharing of payment data
              with Stripe for transaction purposes.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Links to Other Websites</h2>
            <p>
              This Privacy Policy applies only to the Services. The Services may
              contain links to other websites not operated or controlled by
              Scalemate. We are not responsible for the content, accuracy or
              opinions expressed in such websites, and such websites are not
              investigated, monitored or checked for accuracy or completeness by
              us. Please remember that when you use a link to go from the
              Services to another website, our Privacy Policy is no longer in
              effect. Your browsing and interaction on any other website,
              including those that have a link on our platform, is subject to
              that website's own rules and policies. Such third parties may use
              their own cookies or other methods to collect information about
              you.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Cookies</h2>
            <p>
              Scalemate uses "Cookies" to identify the areas of our website that
              you have visited. A Cookie is a small piece of data stored on your
              computer or mobile device by your web browser. We use Cookies to
              enhance the performance and functionality of our website but are
              non-essential to their use. However, without these cookies,
              certain functionality like videos may become unavailable or you
              would be required to enter your login details every time you visit
              the website as we would not be able to remember that you had
              logged in previously. Most web browsers can be set to disable the
              use of Cookies. However, if you disable Cookies, you may not be
              able to access functionality on our website correctly or at all.
              We never place Personally Identifiable Information in Cookies. We
              do not respond to "Do Not Track" (DNT) signals from your browser.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Blocking and disabling cookies and similar technologies</h2>
            <p>
              Wherever you're located you may also set your browser to block
              cookies and similar technologies, but this action may block our
              essential cookies and prevent our website from functioning
              properly, and you may not be able to fully utilize all of its
              features and services. You should also be aware that you may also
              lose some saved information (e.g. saved login details, site
              preferences) if you block cookies on your browser. Different
              browsers make different controls available to you. Disabling a
              cookie or category of cookie does not delete the cookie from your
              browser, you will need to do this yourself from within your
              browser, you should visit your browser's help menu for more
              information.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Remarketing Services</h2>
            <p>
              We use remarketing services. What Is Remarketing? In digital
              marketing, remarketing (or retargeting) is the practice of serving
              ads across the internet to people who have already visited your
              website. It allows your company to seem like they're "following"
              people around the internet by serving ads on the websites and
              platforms they use most. We do not respond to "Do Not Track" (DNT)
              signals from your browser.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Kids' Privacy</h2>
            <p>
              We do not address anyone under the age of 13. We do not knowingly
              collect personally identifiable information from anyone under the
              age of 13. If You are a parent or guardian and You are aware that
              Your child has provided Us with Personal Data, please contact Us.
              If We become aware that We have collected Personal Data from
              anyone under the age of 13 without verification of parental
              consent, We take steps to remove that information from Our
              servers.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Changes To Our Privacy Policy</h2>
            <p>
              We may change our Service and policies, and we may need to make
              changes to this Privacy Policy so that they accurately reflect our
              Service and policies. Unless otherwise required by law, we will
              notify you (for example, through our Service) before we make
              changes to this Privacy Policy and give you an opportunity to
              review them before they go into effect. When we update this
              Privacy Policy — including changes related to OpenAI or Stripe —
              we will notify you via email or our dashboard at least 30 days
              before changes take effect. Then, if you continue to use the
              Service, you will be bound by the updated Privacy Policy. If you
              do not want to agree to this or any updated Privacy Policy, you
              can delete your account.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Third-Party Services</h2>
            <p>
              We may display, include or make available third-party content
              (including data, information, applications and other products
              services) or provide links to third-party websites or services
              ("Third-Party Services").
            </p>
            <p>
              You acknowledge and agree that Scalemate shall not be responsible
              for any Third-Party Services, including their accuracy,
              completeness, timeliness, validity, copyright compliance,
              legality, decency, quality or any other aspect thereof. Scalemate
              does not assume and shall not have any liability or responsibility
              to you or any other person or entity for any Third-Party Services.
            </p>
            <p>
              Third-Party Services and links thereto are provided solely as a
              convenience to you and you access and use them entirely at your
              own risk and subject to such third parties' terms and conditions.
            </p>

            <h3>Third-Party Services We Use</h3>
            <p>
              We partner with certain third-party providers who help us run
              Scalemate, analyze performance, or deliver our Service. Where we
              share personal or usage data with them, we've noted it below. For
              details on how they handle your information, please click through
              to their privacy policies.
            </p>

            <div className={styles.thirdPartyService}>
              <h4>1. EmailListVerify</h4>
              <p>
                <strong>Purpose:</strong> Validate and clean customer email
                addresses during signup.
              </p>
              <p>
                <strong>Data shared:</strong> Email address only.
              </p>
              <p>
                <strong>Privacy terms:</strong>{" "}
                <a
                  href="https://emaillistverify.com/privacy-policy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://emaillistverify.com/privacy-policy
                </a>
              </p>
            </div>

            <div className={styles.thirdPartyService}>
              <h4>2. Hotjar</h4>
              <p>
                <strong>Purpose:</strong> Collect anonymous session analytics
                (page views, clicks, heatmaps) to improve UX.
              </p>
              <p>
                <strong>Data shared:</strong> Device/IP (anonymized), session
                behavior.
              </p>
              <p>
                <strong>Privacy terms:</strong>{" "}
                <a
                  href="https://www.hotjar.com/legal/policies/privacy/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://www.hotjar.com/legal/policies/privacy/
                </a>
              </p>
            </div>

            <div className={styles.thirdPartyService}>
              <h4>3. OpenAI API</h4>
              <p>
                <strong>Purpose:</strong> Process aggregated ad‐performance data
                (e.g., spend, CTR, installs) in order to generate AI-powered
                Recommendations.
              </p>
              <p>
                <strong>Data shared:</strong> Aggregated analytics data only. No
                raw PII is sent.
              </p>
              <p>
                <strong>Privacy terms:</strong>{" "}
                <a
                  href="https://openai.com/policies/privacy-policy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://openai.com/policies/privacy-policy
                </a>
              </p>
            </div>

            <div className={styles.thirdPartyService}>
              <h4>4. TikTok Pixel</h4>
              <p>
                <strong>Purpose:</strong> Track conversion events (e.g.,
                signups) on our site to measure ad performance.
              </p>
              <p>
                <strong>Data shared:</strong> Browser cookies and event data (no
                names or email addresses).
              </p>
              <p>
                <strong>Privacy terms:</strong>{" "}
                <a
                  href="https://www.tiktok.com/legal/page/eea/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://www.tiktok.com/legal/page/eea/privacy
                </a>
              </p>
            </div>

            <div className={styles.thirdPartyService}>
              <h4>5. Facebook Marketing API / Facebook Pixel</h4>
              <p>
                <strong>Purpose:</strong> Upload custom audiences (hashed
                emails) and track on-site conversions for ad retargeting.
              </p>
              <p>
                <strong>Data shared:</strong> Hashed email addresses (for custom
                audiences) and event data (e.g., page visits, form submissions).
              </p>
              <p>
                <strong>Privacy terms:</strong>{" "}
                <a
                  href="https://www.facebook.com/privacy/policy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://www.facebook.com/privacy/policy
                </a>
              </p>
            </div>

            <div className={styles.thirdPartyService}>
              <h4>6. Rollbar</h4>
              <p>
                <strong>Purpose:</strong> Real-time error monitoring and
                debugging of our platform.
              </p>
              <p>
                <strong>Data shared:</strong> Server and client error logs (may
                include anonymized stack traces, file names, and timestamps). No
                directly identifiable user data is sent to Rollbar.
              </p>
              <p>
                <strong>Privacy terms:</strong>{" "}
                <a
                  href="https://docs.rollbar.com/docs/privacy-policy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://docs.rollbar.com/docs/privacy-policy
                </a>
              </p>
            </div>

            <div className={styles.thirdPartyService}>
              <h4>7. DigitalOcean</h4>
              <p>
                <strong>Purpose:</strong> Cloud hosting and infrastructure for
                servers that power Scalemate.
              </p>
              <p>
                <strong>Data shared:</strong> Standard server logs, back-ups,
                and infrastructure metadata. No customer PII is stored by
                DigitalOcean in readable form; all data is encrypted at rest.
              </p>
              <p>
                <strong>Privacy terms:</strong>{" "}
                <a
                  href="https://www.digitalocean.com/legal/privacy-policy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://www.digitalocean.com/legal/privacy-policy
                </a>
              </p>
            </div>

            <div className={styles.thirdPartyService}>
              <h4>8. Stripe</h4>
              <p>
                <strong>Purpose:</strong> Handle subscription billing and
                one-time payments.
              </p>
              <p>
                <strong>Data shared:</strong> Payment method tokens; billing
                email; transaction amount.
              </p>
              <p>
                <strong>Why:</strong> To securely process your credit card or
                other payment methods.
              </p>
              <p>
                <strong>Vendor policy:</strong>{" "}
                <a
                  href="https://stripe.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://stripe.com/privacy
                </a>
              </p>
            </div>
          </div>

          <div className={styles.section}>
            <h2>Facebook Pixel</h2>
            <p>
              Facebook pixel is an analytics tool that allows you to measure the
              effectiveness of your advertising by understanding the actions
              people take on your website/app. You can use the pixel to: Make
              sure your ads are shown to the right people. Facebook pixel may
              collect information from your device when you use the service.
              Facebook pixel collects information that is held in accordance
              with its Privacy Policy
            </p>
          </div>

          <div className={styles.section}>
            <h2>Tracking Technologies</h2>

            <h3>Cookies</h3>
            <p>
              We use Cookies to enhance the performance and functionality of our
              platform but are non-essential to their use. However, without
              these cookies, certain functionality like videos may become
              unavailable or you would be required to enter your login details
              every time you visit the platform as we would not be able to
              remember that you had logged in previously. Our Stripe integration
              may set essential cookies or local storage items to facilitate
              secure payments. We do not respond to 'Do Not Track' (DNT) signals
              from your browser.
            </p>

            <h3>Local Storage</h3>
            <p>
              Local Storage sometimes known as DOM storage, provides web apps
              with methods and protocols for storing client-side data. Web
              storage supports persistent data storage, similar to cookies but
              with a greatly enhanced capacity and no information stored in the
              HTTP request header.
            </p>

            <h3>Sessions</h3>
            <p>
              We use "Sessions" to identify the areas of our platform that you
              have visited. A Session is a small piece of data stored on your
              computer or mobile device by your web browser.
            </p>
          </div>

          <div className={styles.section}>
            <h2>Information about General Data Protection Regulation (GDPR)</h2>
            <p>
              We may be collecting and using information from you if you are
              from the European Economic Area (EEA), and in this section of our
              Privacy Policy we are going to explain exactly how and why is this
              data collected, and how we maintain this data under protection
              from being replicated or used in the wrong way.
            </p>

            <h3>What is GDPR?</h3>
            <p>
              GDPR is an EU-wide privacy and data protection law that regulates
              how EU residents' data is protected by companies and enhances the
              control the EU residents have, over their personal data.
            </p>
            <p>
              The GDPR is relevant to any globally operating company and not
              just the EU-based businesses and EU residents. Our customers' data
              is important irrespective of where they are located, which is why
              we have implemented GDPR controls as our baseline standard for all
              our operations worldwide.
            </p>

            <h3>What is personal data?</h3>
            <p>
              Any data that relates to an identifiable or identified individual.
              GDPR covers a broad spectrum of information that could be used on
              its own, or in combination with other pieces of information, to
              identify a person. Personal data extends beyond a person's name or
              email address. Some examples include financial information,
              political opinions, genetic data, biometric data, IP addresses,
              physical address, sexual orientation, and ethnicity.
            </p>
            <p>The Data Protection Principles include requirements such as:</p>
            <ul>
              <li>
                Personal data collected must be processed in a fair, legal, and
                transparent way and should only be used in a way that a person
                would reasonably expect.
              </li>
              <li>
                Personal data should only be collected to fulfil a specific
                purpose and it should only be used for that purpose.
                Organizations must specify why they need the personal data when
                they collect it.
              </li>
              <li>
                Personal data should be held no longer than necessary to fulfil
                its purpose.
              </li>
              <li>
                People covered by the GDPR have the right to access their own
                personal data. They can also request a copy of their data, and
                that their data be updated, deleted, restricted, or moved to
                another organization.
              </li>
            </ul>

            <h3>Why is GDPR important?</h3>
            <p>
              GDPR adds some new requirements regarding how companies should
              protect individuals' personal data that they collect and process.
              It also raises the stakes for compliance by increasing enforcement
              and imposing greater fines for breach. Beyond these facts it's
              simply the right thing to do. At Scalemate we strongly believe
              that your data privacy is very important and we already have solid
              security and privacy practices in place that go beyond the
              requirements of this new regulation.
            </p>

            <h3>
              Individual Data Subject's Rights - Data Access, Portability and
              Deletion
            </h3>
            <p>
              We are committed to helping our customers meet the data subject
              rights requirements of GDPR. Scalemate processes or stores all
              personal data in fully vetted, DPA compliant vendors. We do store
              all conversation and personal data for up to 6 years unless your
              account is deleted. In which case, we dispose of all data in
              accordance with our Terms of Service and Privacy Policy, but we
              will not hold it longer than 60 days.
            </p>
            <p>
              We are aware that if you are working with EU customers, you need
              to be able to provide them with the ability to access, update,
              retrieve and remove personal data. We got you! We've been set up
              as self service from the start and have always given you access to
              your data and your customers data. Our customer support team is
              here for you to answer any questions you might have about working
              with the API.
            </p>
          </div>

          <div className={styles.section}>
            <h2>California Residents</h2>
            <p>
              The California Consumer Privacy Act (CCPA) requires us to disclose
              categories of Personal Information we collect and how we use it,
              the categories of sources from whom we collect Personal
              Information, and the third parties with whom we share it, which we
              have explained above.
            </p>
            <p>
              We are also required to communicate information about rights
              California residents have under California law. You may exercise
              the following rights:
            </p>
            <ul>
              <li>
                <strong>Right to Know and Access.</strong> You may submit a
                verifiable request for information regarding the: (1) categories
                of Personal Information we collect, use, or share; (2) purposes
                for which categories of Personal Information are collected or
                used by us; (3) categories of sources from which we collect
                Personal Information; and (4) specific pieces of Personal
                Information we have collected about you.
              </li>
              <li>
                <strong>Right to Equal Service.</strong> We will not
                discriminate against you if you exercise your privacy rights.
              </li>
              <li>
                <strong>Right to Delete.</strong> You may submit a verifiable
                request to close your account and we will delete Personal
                Information about you that we have collected.
              </li>
              <li>
                <strong>
                  Request that a business that sells a consumer's personal data,
                  not sell the consumer's personal data.
                </strong>
              </li>
            </ul>
            <p>
              If you make a request, we have one month to respond to you. If you
              would like to exercise any of these rights, please contact us.
            </p>
            <p>We do not sell the Personal Information of our users.</p>
            <p>For more information about these rights, please contact us.</p>
          </div>

          <div className={styles.section}>
            <h2>California Online Privacy Protection Act (CalOPPA)</h2>
            <p>
              CalOPPA requires us to disclose categories of Personal Information
              we collect and how we use it, the categories of sources from whom
              we collect Personal Information, and the third parties with whom
              we share it, which we have explained above.
            </p>
            <p>CalOPPA users have the following rights:</p>
            <ul>
              <li>
                <strong>Right to Know and Access.</strong> You may submit a
                verifiable request for information regarding the: (1) categories
                of Personal Information we collect, use, or share; (2) purposes
                for which categories of Personal Information are collected or
                used by us; (3) categories of sources from which we collect
                Personal Information; and (4) specific pieces of Personal
                Information we have collected about you.
              </li>
              <li>
                <strong>Right to Equal Service.</strong> We will not
                discriminate against you if you exercise your privacy rights.
              </li>
              <li>
                <strong>Right to Delete.</strong> You may submit a verifiable
                request to close your account and we will delete Personal
                Information about you that we have collected.
              </li>
              <li>
                <strong>
                  Right to request that a business that sells a consumer's
                  personal data, not sell the consumer's personal data.
                </strong>
              </li>
            </ul>
            <p>
              If you make a request, we have one month to respond to you. If you
              would like to exercise any of these rights, please contact us.
            </p>
            <p>We do not sell the Personal Information of our users.</p>
            <p>For more information about these rights, please contact us.</p>
          </div>

          <div className={styles.section}>
            <h2>Contact Us</h2>
            <p>Don't hesitate to contact us if you have any question via:</p>
            <div className={styles.contact}>
              <p>
                <strong>Email:</strong>{" "}
                <a href="mailto:info@scalemate.co">info@scalemate.co</a>
              </p>
            </div>
          </div>
        </div>
      </Container>
    </div>
  )
}
